services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo
    volumes:
      - .:/server
      - /server/.venv/
    ports:
      - "8000:8000"
    restart: unless-stopped 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
